from typing import List, Tuple, Optional

class FlibRS:
    def __init__(self, index_path: str, zip_archives_dir: Optional[str] = None) -> None: ...
    def index_exists(self) -> bool: ...
    def build_index(self, inpx_path: str) -> None: ...
    def search(self, query: str) -> List[Tuple[int, str, str, float]]: ...
    def get_info(self, id: int) -> Tuple[str, str]: ...
    def download(self, id: int) -> bool: ...
    def get_file_bytes(self, id: int) -> bytes: ...
